name: build-linux
runs:
  using: composite
  steps:
    - name: build-image
      shell: bash
      run: |
        pushd "$(mktemp -d)"
        curl -f -L --retry 5 https://github.com/tweag/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
        podman build \
          --network host \
          --pull \
          --squash-all \
          --tag rust:alpine-mimalloc \
          .
        popd

    - name: build
      shell: bash
      run: |
        podman run \
          --env RUSTFLAGS="-C target-feature=+crt-static" \
          --init \
          --network host \
          --rm \
          --tmpfs /tmp:exec \
          --volume $PWD:/workspace \
          --workdir /workspace \
          rust:alpine-mimalloc \
          sh -c 'TARGET=$(rustc -vV | sed -n "s|host: ||p") && exec ./build.sh --target $TARGET'

        MIMALLOC_VERBOSE=1 ./bin/wasm-component-ld --help
        MIMALLOC_VERBOSE=1 ./bin/wasm-tools --version
        MIMALLOC_VERBOSE=1 ./bin/wasmtime --version
        MIMALLOC_VERBOSE=1 ./bin/wit-bindgen --version
        MIMALLOC_VERBOSE=1 ./bin/wizer --version

        file ./bin/wasm-component-ld
        file ./bin/wasm-tools
        file ./bin/wasmtime
        file ./bin/wit-bindgen
        file ./bin/wizer

        mkdir wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux
        mv bin wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux
        tar \
          --sort=name \
          --owner=0 --group=0 --numeric-owner \
          --use-compress-program="zstd --ultra -22 --threads=0" \
          -cf wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux.tar.zst \
          wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux
        path: wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux.tar.zst
