name: build

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  x86_64-linux:
    name: linux-${{ matrix.arch }}
    runs-on:
      - X64
      - Linux
      - podman
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build-linux
        uses: ./.github/actions/linux

  aarch64-linux:
    name: linux-${{ matrix.arch }}
    runs-on:
      - ARM64
      - Linux
      - podman
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build-linux
        uses: ./.github/actions/linux

  darwin:
    name: darwin-${{ matrix.arch }}
    runs-on:
      - ARM64
      - macOS
      - asdf
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-deps
        run: |
          rustup target add ${{ matrix.arch }}-apple-darwin

      - name: build
        run: |
          ./build.sh --target ${{ matrix.arch }}-apple-darwin

          file ./bin/wasm-component-ld
          file ./bin/wasm-tools
          file ./bin/wasmtime
          file ./bin/wit-bindgen
          file ./bin/wizer

          mkdir wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}
          mv bin wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}
          tar \
            --use-compress-program="zstd --ultra -22 --threads=0" \
            -cf wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}.tar.zst \
            wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}
          path: wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}.tar.zst

  windows:
    name: windows-${{ matrix.arch }}
    runs-on:
      - X64
      - Windows
      - asdf
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-deps
        run: |
          rustup target add ${{ matrix.arch }}-pc-windows-msvc

      - name: build
        run: |
          mkdir wasm-tools-${{ github.ref_name }}-windows-${{ matrix.arch }}

          cargo install `
            --all-features `
            --root wasm-tools-${{ github.ref_name }}-windows-${{ matrix.arch }} `
            --target ${{ matrix.arch }}-pc-windows-msvc `
            --git https://github.com/haskell-wasm/wizer.git `
            wizer

          cargo install `
            --all-features `
            --root wasm-tools-${{ github.ref_name }}-windows-${{ matrix.arch }} `
            --target ${{ matrix.arch }}-pc-windows-msvc `
            wasmtime-cli wasm-component-ld wasm-tools wit-bindgen-cli

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-tools-${{ github.ref_name }}-windows-${{ matrix.arch }}
          path: wasm-tools-${{ github.ref_name }}-windows-${{ matrix.arch }}
